services:
  php:
    image: teammates-php
    container_name: teammates-php
    build:
      context: ./
      dockerfile: dev.Dockerfile
    environment:
      - TZ=UTC
    entrypoint: "php-fpm"
    volumes:
      - ./:/var/www/teammates:rw,cached
      - socket:/var/run/
    secrets:
      - source: host_ssh_key
        target: /root/.ssh/id_rsa

  messenger-consumer:
    image: teammates-php
    container_name: teammates-messenger-consumer
    environment:
      - TZ=UTC
    entrypoint: "bin/console messenger:consume async -vvv"
    volumes:
      - ./:/var/www/teammates:rw,cached
    secrets:
      - source: host_ssh_key
        target: /root/.ssh/id_rsa
    restart: unless-stopped
    depends_on:
      - php
      - database
      - mailer

  nginx:
    container_name: teammates-nginx
    image: nginx:1.25-alpine3.18
    ports:
      - "${NGINX_WEB_PORT:-8383}:80"
    volumes:
      - ./:/var/www/teammates:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/var/run/
    depends_on:
      - php

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: teammates-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-teammates}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-user}
    ports:
      - "${POSTGRES_PORT:-54322}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "${MAILER_WEB_PORT:-8025}:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
  packfood_db: {}

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  socket: {}

secrets:
  host_ssh_key:
    file: ${SSH_PRIVATE_KEY:-~/.ssh/id_rsa}
