services:
  php:
    image: teammates-php
    container_name: teammates-php
    build:
      context: ./
      dockerfile: dev.Dockerfile
    environment:
      - TZ=UTC
    entrypoint: "php-fpm"
    volumes:
      - ./:/var/www/teammates:rw,cached
      - socket:/var/run/
    secrets:
      - source: host_ssh_key
        target: /root/.ssh/id_rsa

  nginx:
    container_name: teammates-nginx
    image: nginx:1.25-alpine3.18
    ports:
      - "${NGINX_WEB_PORT:-8383}:80"
    volumes:
      - ./:/var/www/teammates:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/var/run/
    depends_on:
      - php

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  packfood_db: {}

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  socket: {}

secrets:
  host_ssh_key:
    file: ${SSH_PRIVATE_KEY:-~/.ssh/id_rsa}
