controllers:
    resource:
        path: ../src/Controller/
        namespace: Teammates\Controller
    type: attribute

user:
    resource:
        path: ../src/User/
        namespace: Teammates\User
    type: attribute

event:
    resource:
        path: ../src/Event/
        namespace: Teammates\Event
    type: attribute
